package dev.annawathe.api.client.inventory;
import dev.doctor4t.wathe.client.gui.screen.ingame.LimitedInventoryScreen; import net.fabricmc.api.EnvType; import net.fabricmc.api.Environment; import net.minecraft.client.font.TextRenderer; import net.minecraft.client.gui.screen.Screen; import net.minecraft.client.gui.widget.ClickableWidget; import net.minecraft.client.network.ClientPlayerEntity; import net.minecraft.util.Identifier; import org.jetbrains.annotations.Nullable; import java.util.*;
@Environment(EnvType.CLIENT) public final class InventoryButtonContext {
    private final Screen screen; private final InventoryScreenType type; private final ClientPlayerEntity player; private final TextRenderer textRenderer; private final InventoryButtonApi.ScreenState state; private final InventoryButtonApi.WidgetAdder adder; private final int width,height,bgX,bgY,bgWidth,bgHeight;
    InventoryButtonContext(Screen screen, InventoryScreenType type, @Nullable ClientPlayerEntity player, TextRenderer textRenderer, InventoryButtonApi.ScreenState state, InventoryButtonApi.WidgetAdder adder, int width, int height, int bgX, int bgY, int bgWidth, int bgHeight) { this.screen=screen;this.type=type;this.player=player;this.textRenderer=textRenderer;this.state=state;this.adder=adder;this.width=width;this.height=height;this.bgX=bgX;this.bgY=bgY;this.bgWidth=bgWidth;this.bgHeight=bgHeight; }
    public Screen screen(){return screen;} public InventoryScreenType type(){return type;} public @Nullable ClientPlayerEntity player(){return player;} public ClientPlayerEntity requirePlayer(){return Objects.requireNonNull(player);}
    public @Nullable LimitedInventoryScreen limitedScreen(){return screen instanceof LimitedInventoryScreen limited?limited:null;} public LimitedInventoryScreen requireLimitedScreen(){return Objects.requireNonNull(limitedScreen(),"This provider requires a LIMITED inventory screen");}
    public TextRenderer textRenderer(){return textRenderer;} public int width(){return width;} public int height(){return height;} public int backgroundX(){return bgX;} public int backgroundY(){return bgY;} public int backgroundWidth(){return bgWidth;} public int backgroundHeight(){return bgHeight;}
    public <T extends ClickableWidget> T addWidget(T widget){return (T)adder.add(widget);} public <T extends ClickableWidget> T addWidget(Identifier group,T widget){T added=addWidget(widget);state.addToGroup(group,added);return added;} public void replaceGroup(Identifier id,Collection<? extends ClickableWidget> widgets){clearGroup(id);for(ClickableWidget widget:widgets)addWidget(id,widget);} public void clearGroup(Identifier id){state.clearGroup(id);} public void setGroupVisible(Identifier id,boolean visible){state.setGroupVisible(id,visible);}
}
