package dev.annawathe.api.client.inventory;
import net.fabricmc.api.EnvType; import net.fabricmc.api.Environment; import net.minecraft.client.font.TextRenderer; import net.minecraft.client.gui.DrawContext; import net.minecraft.client.gui.screen.Screen; import net.minecraft.client.gui.widget.ClickableWidget; import net.minecraft.client.network.ClientPlayerEntity; import net.minecraft.util.Identifier; import java.util.*;
@Environment(EnvType.CLIENT) public final class InventoryButtonApi {
    public static final int DEFAULT_PRIORITY=0; private static final List<Entry> PROVIDERS=new ArrayList<>(); private static final Map<Screen,ScreenState> STATES=new WeakHashMap<>(); private static long order;
    private InventoryButtonApi(){}
    public static synchronized void registerProvider(Identifier id,int priority,InventoryButtonProvider provider){PROVIDERS.removeIf(e->e.id.equals(id));PROVIDERS.add(new Entry(id,priority,order++,provider));PROVIDERS.sort(Comparator.<Entry>comparingInt(Entry::priority).reversed().thenComparing(Comparator.comparingLong(Entry::order).reversed()));}
    public static void initializeScreen(Screen screen,InventoryScreenType type,ClientPlayerEntity player,TextRenderer renderer,WidgetAdder adder,int width,int height,int bgX,int bgY,int bgWidth,int bgHeight){closeScreen(screen);ScreenState state=new ScreenState(screen,type,player,renderer,adder,width,height,bgX,bgY,bgWidth,bgHeight);synchronized(STATES){STATES.put(screen,state);}for(Entry entry:providerSnapshot()){InventoryButtonExtension extension=entry.provider.create(state.context);if(extension!=null){state.extensions.add(extension);extension.init(state.context);}}}
    public static void tickScreen(Screen screen){ScreenState s=get(screen);if(s!=null)for(InventoryButtonExtension e:List.copyOf(s.extensions))e.tick(s.context);}
    public static void renderScreen(Screen screen,DrawContext draw,int mouseX,int mouseY,float delta){ScreenState s=get(screen);if(s!=null)for(InventoryButtonExtension e:List.copyOf(s.extensions))e.render(s.context,draw,mouseX,mouseY,delta);}
    public static boolean allowInventoryKeyClose(Screen screen,int keyCode,int scanCode){ScreenState s=get(screen);if(s==null)return true;for(InventoryButtonExtension e:List.copyOf(s.extensions))if(!e.allowInventoryKeyClose(s.context,keyCode,scanCode))return false;return true;}
    public static void closeScreen(Screen screen){ScreenState s; synchronized(STATES){s=STATES.remove(screen);}if(s!=null){for(InventoryButtonExtension e:List.copyOf(s.extensions))e.close(s.context);s.clearAllGroups();}}
    public static void reset(){List<Screen> screens; synchronized(STATES){screens=List.copyOf(STATES.keySet());}for(Screen screen:screens)closeScreen(screen);}
    private static synchronized List<Entry> providerSnapshot(){return List.copyOf(PROVIDERS);}private static ScreenState get(Screen screen){synchronized(STATES){return STATES.get(screen);}}
    @FunctionalInterface public interface WidgetAdder{ClickableWidget add(ClickableWidget widget);}
    static final class ScreenState {final InventoryButtonContext context;final List<InventoryButtonExtension> extensions=new ArrayList<>();final Map<Identifier,List<ClickableWidget>> groups=new HashMap<>();ScreenState(Screen screen,InventoryScreenType type,ClientPlayerEntity player,TextRenderer renderer,WidgetAdder adder,int w,int h,int x,int y,int bw,int bh){context=new InventoryButtonContext(screen,type,player,renderer,this,adder,w,h,x,y,bw,bh);}void addToGroup(Identifier id,ClickableWidget w){groups.computeIfAbsent(id,k->new ArrayList<>()).add(w);}void clearGroup(Identifier id){List<ClickableWidget> ws=groups.remove(id);if(ws!=null)for(ClickableWidget w:ws){w.visible=false;w.active=false;w.setFocused(false);}}void setGroupVisible(Identifier id,boolean visible){List<ClickableWidget> ws=groups.get(id);if(ws!=null)for(ClickableWidget w:ws){w.visible=visible;w.active=visible;if(!visible)w.setFocused(false);}}void clearAllGroups(){for(Identifier id:List.copyOf(groups.keySet()))clearGroup(id);}}
    private record Entry(Identifier id,int priority,long order,InventoryButtonProvider provider){}
}
