package dev.annawathe.client.gui;
import dev.annawathe.api.economy.EconomyApi;
import dev.annawathe.api.shop.ShopApi;
import net.minecraft.client.font.TextRenderer; import net.minecraft.client.gui.DrawContext; import net.minecraft.client.network.ClientPlayerEntity; import net.minecraft.util.Identifier; import net.minecraft.util.math.MathHelper; import java.util.*;
/** 多货币余额 HUD；余额归零时保留一小段动画再淡出，避免购买瞬间跳变。 */
public final class AnnaStoreRenderer {
    private static final Map<Identifier,Line> LINES=new HashMap<>(); private AnnaStoreRenderer(){}
    public static void renderHud(TextRenderer renderer,ClientPlayerEntity player,DrawContext context,float delta){List<EconomyApi.CurrencyBalance> balances=EconomyApi.getVisibleCurrencyBalances(player,ShopApi.hasShop(player));Set<Identifier> present=new HashSet<>();for(int i=0;i<balances.size();i++){var b=balances.get(i);present.add(b.currency().id());LINES.computeIfAbsent(b.currency().id(),id->new Line(b.currency().icon())).visible(b.amount(),i,delta);}for(var e:LINES.entrySet())if(!present.contains(e.getKey()))e.getValue().hidden(balances.size(),delta);LINES.entrySet().removeIf(e->e.getValue().gone());List<Line> ordered=new ArrayList<>(LINES.values());ordered.sort(Comparator.comparingDouble(l->l.offset));for(Line line:ordered){context.getMatrices().push();context.getMatrices().translate(context.getScaledWindowWidth()-12,6+line.offset*10,0);line.render(renderer,context,delta);context.getMatrices().pop();}}
    public static void tick(){LINES.values().forEach(l->l.number.update());} public static void reset(){LINES.clear();}
    private static final class Line{final String icon;final Number number=new Number();float offset,alpha=.07f,flash;boolean exiting;Line(String icon){this.icon=icon;}void visible(int amount,int index,float d){exiting=false;if(number.target!=amount){flash=amount>number.target?.6f:-.6f;number.set(amount);}offset=MathHelper.lerp(d/8,offset,index);alpha=MathHelper.lerp(d/12,alpha,1);flash=MathHelper.lerp(d/16,flash,0);}void hidden(int index,float d){exiting=true;number.set(0);offset=MathHelper.lerp(d/8,offset,index);alpha=MathHelper.lerp(d/12,alpha,number.settled()?0:1);}boolean gone(){return exiting&&number.settled()&&alpha<.02f;}void render(TextRenderer r,DrawContext c,float d){int color=MathHelper.packRgb(flash>0?1-flash:1,flash<0?1+flash:1,1-Math.abs(flash))&0xFFFFFF;color|=MathHelper.clamp((int)(alpha*255),0,255)<<24;number.render(r,c,icon,color,d);}}
    private static final class Number{final List<Digit> digits=new ArrayList<>();int target;void set(int value){target=Math.max(0,value);while(digits.size()<String.valueOf(target).length())digits.add(new Digit(digits.isEmpty()));for(int i=0;i<digits.size();i++)digits.get(i).target=i==0?target/(float)Math.pow(10,i):(int)(target/Math.pow(10,i));}void update(){digits.forEach(Digit::update);}boolean settled(){return digits.stream().allMatch(d->Math.abs(d.value-d.target)<.01f);}void render(TextRenderer r,DrawContext c,String icon,int color,float delta){c.drawTextWithShadow(r,icon,0,0,color);int x=-8;for(Digit d:digits){c.getMatrices().push();c.getMatrices().translate(x,0,0);d.render(r,c,color,delta);c.getMatrices().pop();x-=8;}}}
    private static final class Digit{final boolean force;float target,value,last;Digit(boolean force){this.force=force;}void update(){last=value;value=MathHelper.lerp(.15f,value,target);if(Math.abs(value-target)<.01f)value=target;}void render(TextRenderer r,DrawContext c,int color,float d){float v=MathHelper.lerp(d,last,value);int a=MathHelper.floor(v)%10,n=MathHelper.floor(v+1)%10;float off=v%1;int rgb=color&0xFFFFFF,parentAlpha=color>>>24;float leadingAlpha=v<1&&!force?v:1;int base=rgb|MathHelper.clamp(Math.round(parentAlpha*(1-Math.abs(off))*leadingAlpha),0,255)<<24,next=rgb|MathHelper.clamp(Math.round(parentAlpha*Math.abs(off)),0,255)<<24;c.getMatrices().push();c.getMatrices().translate(0,-off*(r.fontHeight+2),0);/* 极低 alpha 会被 TextRenderer 当成不透明旧颜色，必须达到 4 才真正绘制。 */if((force||v>=1)&&(base&0xFC000000)!=0)c.drawTextWithShadow(r,""+a,0,0,base);if((next&0xFC000000)!=0)c.drawTextWithShadow(r,""+n,0,r.fontHeight+2,next);c.getMatrices().pop();}}
}
