package dev.annawathe.api.client.mood;
import dev.annawathe.client.psychosis.AnnaPsychosisVisualState;
import dev.doctor4t.wathe.api.Role; import dev.doctor4t.wathe.cca.GameWorldComponent; import dev.doctor4t.wathe.cca.PlayerMoodComponent; import dev.doctor4t.wathe.game.GameFunctions;
import net.minecraft.client.render.entity.model.BipedEntityModel; import net.minecraft.entity.LivingEntity; import net.minecraft.entity.player.PlayerEntity; import net.minecraft.item.Item; import net.minecraft.item.ItemStack; import net.minecraft.registry.tag.TagKey; import net.minecraft.util.Hand; import net.minecraft.util.Identifier; import net.minecraft.util.math.random.Random; import org.jetbrains.annotations.Nullable; import java.util.*;
/**
 * 低心情幻觉手持物 provider 链。
 * 结果只存在观察者客户端，不修改目标真实背包，也不能作为服务端攻击依据。
 */
public final class PsychosisItemApi {
 public static final int DEFAULT_PRIORITY=0; private static final List<Entry> PROVIDERS=new ArrayList<>(); private static long order; private PsychosisItemApi(){}
 public static synchronized void registerProvider(Identifier id,int priority,Provider provider){PROVIDERS.removeIf(e->e.id.equals(id));PROVIDERS.add(new Entry(id,priority,order++,provider));PROVIDERS.sort(Comparator.comparingInt(Entry::priority).reversed().thenComparing(Comparator.comparingLong(Entry::order).reversed()));}
 public static synchronized boolean hasProviders(){return !PROVIDERS.isEmpty();}
 public static @Nullable Result resolve(Context c,@Nullable Result def){List<Entry> s; synchronized(PROVIDERS){s=List.copyOf(PROVIDERS);}for(Entry e:s)if(e.priority>0){Result r=e.provider.resolve(c);if(r!=null&&r.handled)return r;}if(def!=null&&def.handled)return def;for(Entry e:s)if(e.priority<=0){Result r=e.provider.resolve(c);if(r!=null&&r.handled)return r;}return null;}
 public static ItemStack resolveRenderStack(@Nullable PlayerEntity viewer,LivingEntity holder,Hand hand,ItemStack actual){if(!(holder instanceof PlayerEntity target)||!canRender(viewer,target))return actual;ItemStack custom=AnnaPsychosisVisualState.get(viewer.getUuid(),target.getUuid(),hand);if(custom!=null)return custom;ItemStack original=PlayerMoodComponent.KEY.get(viewer).getPsychosisItems().get(target.getUuid());return original==null?actual:original.copy();}
 public static @Nullable BipedEntityModel.ArmPose resolveRenderArmPose(@Nullable PlayerEntity viewer,LivingEntity holder,Hand hand){if(!(holder instanceof PlayerEntity target)||!canRender(viewer,target))return null;return AnnaPsychosisVisualState.getPose(viewer.getUuid(),target.getUuid(),hand);}
 private static boolean canRender(@Nullable PlayerEntity viewer,PlayerEntity target){return viewer!=null&&viewer.getWorld()==target.getWorld()&&GameWorldComponent.KEY.get(viewer.getWorld()).isRunning()&&GameFunctions.isPlayerAliveAndSurvival(viewer)&&GameFunctions.isPlayerAliveAndSurvival(target);}
 @FunctionalInterface public interface Provider{@Nullable Result resolve(Context context);}
 public record Context(PlayerEntity viewer,PlayerEntity target,Hand hand,ItemStack actualStack,PlayerMoodComponent moodComponent,GameWorldComponent gameWorld,@Nullable Role targetRole,boolean defaultHallucinationEnabled,boolean reroll,Random random){public @Nullable Item randomItem(Collection<Item> items){return items.isEmpty()?null:items.stream().skip(random.nextInt(items.size())).findFirst().orElse(null);}public @Nullable Item randomTaggedItem(TagKey<Item> tag){return target.getRegistryManager().createRegistryLookup().getOrThrow(net.minecraft.registry.RegistryKeys.ITEM).getOptional(tag).map(list->list.stream().map(e->e.value()).toList()).map(this::randomItem).orElse(null);}}
 public static final class Result{public static final Result PASS=new Result(false,ItemStack.EMPTY,null);private final boolean handled;private final ItemStack stack;private final @Nullable BipedEntityModel.ArmPose pose;private Result(boolean handled,ItemStack stack,@Nullable BipedEntityModel.ArmPose pose){this.handled=handled;this.stack=stack;this.pose=pose;}public static Result item(ItemStack s){return new Result(true,s.copy(),null);}public static Result item(Item i){return item(new ItemStack(i));}public static Result itemWithPose(ItemStack s,BipedEntityModel.ArmPose p){return new Result(true,s.copy(),p);}public static Result emptyWithPose(BipedEntityModel.ArmPose p){return new Result(true,ItemStack.EMPTY,p);}public boolean handled(){return handled;}public ItemStack stack(){return stack;}public @Nullable BipedEntityModel.ArmPose armPose(){return pose;}}
 private record Entry(Identifier id,int priority,long order,Provider provider){}
}
