package dev.annawathe.api.win;
import net.minecraft.entity.player.PlayerEntity; import net.minecraft.nbt.*; import net.minecraft.util.Identifier; import java.util.*;
public record CustomVictory(Identifier id,String announcementTranslationKey,String detailTranslationKey,String fallbackTitle,int color,List<UUID> winnerUuids,CustomVictoryGroup winnerGroup){
 public CustomVictory{winnerUuids=List.copyOf(winnerUuids);}
 public boolean isWinner(UUID u){return u!=null&&winnerUuids.contains(u);}
 public NbtCompound writeToNbt(){NbtCompound t=new NbtCompound();t.putString("id",id.toString());t.putString("announcement",announcementTranslationKey);t.putString("detail",detailTranslationKey);t.putString("fallback",fallbackTitle);t.putInt("color",color);NbtList l=new NbtList();for(UUID u:winnerUuids)l.add(NbtHelper.fromUuid(u));t.put("winners",l);t.put("group",winnerGroup.writeToNbt());return t;}
 public static CustomVictory fromNbt(NbtCompound t){List<UUID> l=new ArrayList<>();for(NbtElement e:t.getList("winners",NbtElement.INT_ARRAY_TYPE))l.add(NbtHelper.toUuid(e));Identifier i=Identifier.tryParse(t.getString("id"));if(i==null)i=Identifier.of("annawathe","custom");return new CustomVictory(i,t.getString("announcement"),t.getString("detail"),t.getString("fallback"),t.getInt("color"),l,CustomVictoryGroup.fromNbt(t.getCompound("group")));}
 public static Builder builder(Identifier id,int color){return new Builder(id,color);} public static CustomVictory of(Identifier id,int color,Collection<? extends PlayerEntity> p){return builder(id,color).winnersFromPlayers(p).build();}
 public static final class Builder{final Identifier id;final int color;String announcement,detail,fallback;String title;List<UUID>w=List.of();Builder(Identifier i,int c){id=i;color=c;announcement="announcement.win."+i.getNamespace()+"."+i.getPath();detail="game.win."+i.getNamespace()+"."+i.getPath();title="announcement.role."+i.getNamespace()+"."+i.getPath();fallback=CustomVictoryGroup.pretty(i.getPath());}public Builder announcementTranslationKey(String s){announcement=s;return this;}public Builder detailTranslationKey(String s){detail=s;return this;}public Builder titleTranslationKey(String s){title=s;return this;}public Builder fallbackTitle(String s){fallback=s;return this;}public Builder winners(Collection<UUID>s){w=List.copyOf(s);return this;}public Builder winnersFromPlayers(Collection<? extends PlayerEntity>s){w=CustomVictoryGroup.uuids(s);return this;}public CustomVictory build(){return new CustomVictory(id,announcement,detail,fallback,color,w,new CustomVictoryGroup(title,fallback,color,w));}}
}
